name: mmelo
favicon: null
layout_spectrum: 0.16909
typography_spectrum: 0.72669
title: mmelo boutique confections
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f3e8'
    - '#28040c'
    - '#d50916'
    - '#cb8e30'
    - '#0b406c'
  brandStrength: 0.1875
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
