name: mmelo
favicon: null
layout_spectrum: 0.7645031833089888
typography_spectrum: 0.9180681959260255
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8375839062500745
  lightness: 0.6431119795888662
  saturation: 0.2679689018987119
  rhythmicContrast: 0.4884334846865386
purpose: []
